### ISSUE TITLE
Support AWS provider in version 3.xx

### ISSUE THREAD

**Issue by cornerman** [kjagiello/terraform-aws-codepipeline-slack-notifications#10]
Can we support the AWS provider in version 3? I have some difficulties with the old version 2, but the version constraint in this module does not support it.

To me, it seems as if everything is working after upgrading it manually.

**Comment by kjagiello** [comment]
I've just tested it out and you are right. We can easily relax the version constraint as this modules seems to be working perfectly fine with v3.

**Comment by kjagiello** [comment]
Released now in v1.1.2!

**Comment by cornerman** [comment]
Nice, thank you very much <3
