### ISSUE TITLE
KeyError: 'pipeline'

### ISSUE THREAD

**Issue by neidiom** [kjagiello/terraform-aws-codepipeline-slack-notifications#22]
I am getting the error below. As far as I can see this message is missing https://github.com/kjagiello/terraform-aws-codepipeline-slack-notifications/blob/master/lambdas/notifier/tests.py#L20

maybe a aws_cloudwatch_event_rule is missing?

````
[ERROR] KeyError: 'pipeline'
Traceback (most recent call last):
  File "/var/task/slack.py", line 136, in handler
    payload = build_slack_message_from_event(event)
  File "/var/task/slack.py", line 80, in build_slack_message_from_event
    pipeline_name = message["detail"]["pipeline"]
````

**Comment by kjagiello** [comment]
I cannot reproduce this, unfortunately. In case you encounter this issue, feel free to reopen this and post the event that CodePipeline event that triggered it (you should be able to find it in the lambda logs).
