### ISSUE TITLE
Permission error running Lambda

### ISSUE THREAD

**Issue by xgp** [kjagiello/terraform-aws-codepipeline-slack-notifications#8]
Hi! Thanks for the great module. I'm having some problems when the notifier Lambda runs. I see the following permissions error in the log stream:

```
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/notifier.py'Traceback (most recent call last):  File "/var/lang/lib/python3.8/imp.py", line 300, in find_module    with open(file_path, 'rb') as file:
```

any ideas?

**Comment by xgp** [comment]
Quick update. The `notifier.py` file in the `.terraform/modules/code_pipeline.codepipeline_notifications/lambdas/notifier.zip` bundle has permissions `-rw-rw----`. When I change it to `-rw-r--r--` and destroy/create the lambda, it works fine. FYI I'm using release 1.1.0.

**Comment by kjagiello** [comment]
Hi and thanks for your bug report! What version of Terraform are you running? And what permissions does the source notifier.py have on your system?

**Comment by xgp** [comment]
Terraform version: 0.13.2

```
[garth:production (master)]$ ls -lah .terraform/modules/code_pipeline.codepipeline_notifications/lambdas/
total 8
drwxrwx---   4 garth  staff   128B Jan 20 22:19 .
drwxrwx---  13 garth  staff   416B Jan 20 20:41 ..
drwxrwx---   4 garth  staff   128B Jan 20 20:41 notifier
-rw-rw----   1 garth  staff   1.5K Jan 20 22:19 notifier.zip
[garth:production (master)]$ ls -lah .terraform/modules/code_pipeline.codepipeline_notifications/lambdas/notifier
total 24
drwxrwx---  4 garth  staff   128B Jan 20 20:41 .
drwxrwx---  4 garth  staff   128B Jan 20 22:19 ..
-rw-rw----  1 garth  staff   3.8K Jan 20 20:41 notifier.py
-rw-rw----  1 garth  staff   5.4K Jan 20 20:41 tests.py
```

**Comment by kjagiello** [comment]
Great, thanks! I'll look into it and get back to you!

**Comment by kjagiello** [comment]
This might give you some clue regarding what might be the issue. https://github.com/hashicorp/terraform-provider-archive/issues/59 It seems like you possibly have custom umask set? Nevertheless, it looks like I'll not be able to control the access control flags in the generated archive from the module as `archive_file` does not expose any way of doing that.

**Comment by xgp** [comment]
Thanks for following up. Everyone on my team seems to have the same problem, so it may be how we have our environments set up. I'll check.
